'use client';

import { useState } from 'react';
import { Reveal } from '@/components/Reveal';
import { ArrowIcon, CheckIcon, CoinsIcon, GiftIcon, TwitchIcon } from '@/components/icons';

export default function GetPaidPage() {
  const [handle, setHandle] = useState('');
  const [checked, setChecked] = useState(false);
  return <div className="page-wrap content-page get-paid-page">
    <Reveal><section className="creator-hero"><div><div className="hero-badge"><GiftIcon size={14}/>For Twitch creators</div><h1>Your community can launch.<br/><span className="accent-text">You stay connected to the upside.</span></h1><p>A simple creator-facing page for checking tokens linked to your Twitch handle and the fees routed to you.</p><div className="claim-search"><TwitchIcon size={19}/><input value={handle} onChange={e=>{setHandle(e.target.value);setChecked(false)}} placeholder="your Twitch handle"/><button onClick={()=>setChecked(true)}>Check my page<ArrowIcon size={16}/></button></div>{checked&&<div className="claim-result"><CheckIcon size={16}/><span>{handle ? `@${handle.replace('@','')} is ready for creator lookup.` : 'Enter a Twitch handle first.'}</span></div>}<div className="creator-kpis"><div><span>CREATOR FEES ROUTED</span><strong>$12,884.42</strong></div><div><span>TWITCH CREATORS</span><strong>122</strong></div><div><span>LINKED TOKENS</span><strong>169</strong></div></div></div><div className="creator-phone"><div className="phone-top"><span>9:41</span><i/></div><div className="phone-alert"><TwitchIcon size={21}/><div><strong>subbed routed creator fees</strong><span>from a Pons token</span></div><GiftIcon size={18}/></div><div className="phone-center"><div className="avatar huge">KC</div><strong>@kaicenat</strong><span>Creator dashboard</span></div><div className="phone-balance"><span>Available</span><strong>$1,284.22</strong><div className="balance-line"><i/></div><button>View activity</button></div></div></section></Reveal>
    <Reveal><section className="flow-section"><div className="eyebrow">THE PATH</div><h2>From a Pons trade to the creator page.</h2><div className="flow-track">{[['Trade','Pons'],['Creator fee','generated'],['Route','creator-linked'],['Ledger','tracked'],['Creator','visible']].map(([a,b],i)=><div className="flow-node" key={a}><div className="flow-icon">{i===0?<CoinsIcon/>:i===4?<TwitchIcon/>:<GiftIcon/>}</div><strong>{a}</strong><span>{b}</span>{i<4&&<ArrowIcon size={16}/>}</div>)}</div></section></Reveal>
    <Reveal><section className="faq-grid"><div><div className="eyebrow">QUESTIONS</div><h2>Straight answers.</h2><p className="muted">This pass stays intentionally product-level until the exact Pons payout mechanics are wired.</p></div><div className="faq-list"><details open><summary>Do I have to connect anything?</summary><p>Not in the public discovery experience. Wallet connection is only used when a user launches or performs an on-chain action.</p></details><details><summary>Is this affiliated with Twitch?</summary><p>No. This is a third-party launchpad concept built around public Twitch creator identities.</p></details><details><summary>Where are tokens launched?</summary><p>On Pons, with Robinhood Chain shown as the target network in the product interface.</p></details></div></section></Reveal>
  </div>;
}
